### PR TITLE
Removed a byebug to get twitter login functioning

### PR DESCRIPTION
**Pull request by michelleambrisco**

### CODE REVIEW

**Comment by MLee21** [comment]
In the user login test, isn't "should have" deprecated?

**Comment by michelleambrisco** [comment]
I think I'll just delete that spec for now because I wasn't able to figure out how to test the twitter login.

**Comment by tleskin** [comment]
@MLee21 @MichelleGolle Is this all okay to merge?

**Comment by tleskin** [comment]
After looking over it, it all looked pretty good, so I merged.

**Pull request merged**
